#include "DrawerActor.h"
#include "Components/StaticMeshComponent.h"
#include "Components/TimelineComponent.h"
#include "Engine/World.h"
#include "Curves/CurveFloat.h"
#include "UObject/ConstructorHelpers.h"
#include "GameFramework/Actor.h"
#include "Components/PrimitiveComponent.h"
#include "Components/SceneComponent.h"

// 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
// ?? 瞪薯
// - ④渦(.h)縑 檜嘐 嬴楚 Щ煎ぷじ/л熱菟檜 氈棻堅 陛薑м棲棻
//   UPROPERTY(VisibleAnywhere) UStaticMeshComponent* DrawerMesh;
//   UPROPERTY(VisibleAnywhere) UTimelineComponent* OpenTimeline;
//   UPROPERTY(EditAnywhere)    UCurveFloat* OpenCurve;
//   UPROPERTY(EditAnywhere)    float OpenDistance;
//   UPROPERTY(EditAnywhere)    AActor* DiaryActor;        // 憮奧 寰 橾晦濰 擋攪(顫殮 薯и X)
//   bool bIsOpen; FVector StartLocation;
//   void HandleDrawerProgress(float Value);
//   void OpenDrawer();
//   // CloseDrawer() 橈戲賊 蹺陛 寰 п紫 翕濛л (翮葡虜 籀葬).
// 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式

ADrawerActor::ADrawerActor()
{
    PrimaryActorTick.bCanEverTick = true;

    DrawerMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DrawerMesh"));
    RootComponent = DrawerMesh;

    OpenTimeline = CreateDefaultSubobject<UTimelineComponent>(TEXT("OpenTimeline"));

    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    // ? 晦獄 醱給 撲薑
    // 1) 賅萇 瓣割 Block戲煎 蟾晦
    // 2) 鼻濛辨 塭檣お溯檜蝶(ECC_Visibility)朝 "殘 鼻鷓"縑摹 Block 嶸雖
    //    (翮萵 陽虜 Ignore煎 瞪)
    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    DrawerMesh->SetCollisionProfileName(TEXT("BlockAllDynamic"));
    DrawerMesh->SetCollisionResponseToAllChannels(ECR_Block);                 // [醞蹂] 試盪 瞪羹 Block
    DrawerMesh->SetCollisionResponseToChannel(ECC_Visibility, ECR_Block);     // 鼻濛辨 お溯檜蝶 虞擠(殘 鼻鷓)

    // 僭葬/螃幗椰 晦獄 高 嶸雖 (в蹂 衛 Щ煎薛お 瑙縑 蜃啪 褻薑)
    DrawerMesh->SetGenerateOverlapEvents(false);
}

void ADrawerActor::BeginPlay()
{
    Super::BeginPlay();
    StartLocation = GetActorLocation();

    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    // ? 顫歜塭檣/醴粽 遽綠
    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    if (!OpenCurve)
    {
        UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] OpenCurve is missing, creating default curve."));

        OpenCurve = NewObject<UCurveFloat>(this, TEXT("AutoCurve"));
        OpenCurve->FloatCurve.AddKey(0.0f, 0.0f);
        OpenCurve->FloatCurve.AddKey(1.0f, 1.0f);
    }

    if (OpenCurve)
    {
        FOnTimelineFloat ProgressFunction;
        ProgressFunction.BindUFunction(this, FName("HandleDrawerProgress"));
        OpenTimeline->AddInterpFloat(OpenCurve, ProgressFunction);
        UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] Timeline bound successfully for %s"), *GetName());
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("[Drawer Debug] ? OpenCurve creation failed for %s"), *GetName());
    }

    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    // ? 橾晦濰 擋攪陛 雖薑腎橫 氈戲賊 睡雜 塽 屬葬瞪 爾薑
    //  - 罹晦憮朝 DiaryPickup 顫殮擊 霜蕾 include/曖襄ж雖 彊蝗棲棻.
    //  - 頂睡曖 UStaticMeshComponent蒂 瓊嬴 Visibility=Block 爾濰
    // 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
    if (DiaryActor)
    {
        // 睡雜 (錳楚 氈湍 啻 煎霜 嶸雖)
        DiaryActor->AttachToActor(this, FAttachmentTransformRules::KeepWorldTransform);
        UE_LOG(LogTemp, Warning, TEXT("[Drawer] Attached DiaryActor: %s"), *DiaryActor->GetName());

        // 橾晦濰曖 UStaticMeshComponent 瓊嬴憮 Visibility=Block 爾濰
        if (UStaticMeshComponent* DiaryMesh = DiaryActor->FindComponentByClass<UStaticMeshComponent>())
        {
            DiaryMesh->SetCollisionEnabled(ECollisionEnabled::QueryOnly);                // お溯檜蝶 瞪辨檜賊 梃莠
            DiaryMesh->SetCollisionResponseToAllChannels(ECR_Ignore);
            DiaryMesh->SetCollisionResponseToChannel(ECC_Visibility, ECR_Block);         // 鼻濛辨 お溯檜蝶縑虜 勘葬啪

            UE_LOG(LogTemp, Warning, TEXT("[Drawer] Diary mesh collision set (QueryOnly, Visibility=Block)"));
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("[Drawer] ? DiaryActor has no UStaticMeshComponent"));
        }
    }

    // 鼻鷓 渾Щ
    UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] BeginPlay: DrawerMesh Vis=%d, IsOpen=%d"),
        (int32)DrawerMesh->GetCollisionResponseToChannel(ECC_Visibility), (int32)bIsOpen);
}

void ADrawerActor::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    // 顫歜塭檣 熱翕 偵褐(闡ん凱お 濠翕 Tick檜 嬴棋 唳辦 渠綠)
    if (OpenTimeline)
        OpenTimeline->TickComponent(DeltaTime, ELevelTick::LEVELTICK_TimeOnly, nullptr);

    // 啻 晦襄 ※睡萄毀啪 翮晦§ 爾除 囀萄 嶸雖
    if (bIsOpen)
    {
        static float Alpha = 0.f;
        Alpha = FMath::Clamp(Alpha + DeltaTime * 0.8f, 0.f, 1.f);

        float SmoothAlpha = FMath::InterpEaseInOut(0.f, 1.f, Alpha, 2.5f);
        FVector TargetLocation = StartLocation + GetActorRightVector() * (OpenDistance * SmoothAlpha);
        SetActorLocation(TargetLocation);

        if (Alpha >= 1.f)
            bIsOpen = false;
    }
}

void ADrawerActor::HandleDrawerProgress(float Value)
{
    FVector NewLocation = StartLocation + GetActorRightVector() * (OpenDistance * Value);
    SetActorLocation(NewLocation);

    UE_LOG(LogTemp, Warning, TEXT("[Drawer] HandleDrawerProgress Value=%.2f | Location=%s"),
        Value, *NewLocation.ToString());
}

// 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
// ? 翮晦: 塭檣お溯檜蝶蒂 橾晦濰戲煎 ※鱔婁§衛酈朝 р褕
//  - 翮葬朝 牖除縑虜 DrawerMesh曖 Visibility蒂 Ignore煎 夥翎
//  - 僭葬/棻艇 瓣割 Block 鼻鷓朝 斜渠煎 嶸雖 ⊥ 憮奧擎 罹瞪 撮啗諦 醱給л
// 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
void ADrawerActor::OpenDrawer()
{
    UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] OpenDrawer() called. bIsOpen=%d, OpenCurve=%s"),
        bIsOpen, *GetNameSafe(OpenCurve));

    if (bIsOpen || !OpenCurve)
    {
        UE_LOG(LogTemp, Error, TEXT("[Drawer Debug] ? Drawer cannot open. (Already open or Curve missing)"));
        return;
    }

    bIsOpen = true;

    // ≦ р褕: ※翮葬朝 翕寰§縛 鼻濛辨 お溯檜蝶陛 憮奧擊 鼠衛ж紫煙
    //   (橾晦濰(mesh)擎 Visibility=Block 鼻鷓檜嘎煎, 埠夥煎 橾晦濰縑 お溯檜蝶陛 湊擠)
    DrawerMesh->SetCollisionResponseToChannel(ECC_Visibility, ECR_Ignore);
    UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] DrawerMesh Visibility=Ignore (trace pass-through enabled)"));

    // в蹂縑 評塭 翮葬朝 翕寰 螃幗椰 檜漸お蒂 莖堅 談戲賊 嬴楚 輿戮 п薯
    // DrawerMesh->SetGenerateOverlapEvents(false);

    if (OpenTimeline)
    {
        OpenTimeline->PlayFromStart();
        UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] Ⅱ Drawer Timeline started for %s"), *GetName());
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("[Drawer Debug] ? Timeline is null!"));
    }
}

// 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
// (摹鷗) 殘晦 л熱陛 氈棻賊, 殘 陽 棻衛 Visibility Block戲煎 犒錳
// ④渦縑 CloseDrawer 摹樹檜 橈棻賊 檜 л熱朝 儅楞п紫 鼠寞м棲棻.
// 式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式式
void ADrawerActor::CloseDrawer()
{
    // 殘 隆 棻衛 お溯檜蝶蒂 虞嬴, 憮奧檜 橾晦濰擊 陛葬紫煙
    DrawerMesh->SetCollisionResponseToChannel(ECC_Visibility, ECR_Block);
    // DrawerMesh->SetGenerateOverlapEvents(true); // в蹂衛

    if (OpenTimeline)
    {
        OpenTimeline->Reverse();
        UE_LOG(LogTemp, Warning, TEXT("[Drawer Debug] ９ Drawer Timeline reversed (closing) for %s"), *GetName());
    }
}
